### ISSUE TITLE
Improve fuzzy search regular expression

### ISSUE THREAD

**Issue by jcs090218** [jcs-elpa/searcher#4]
Current fuzzy search is implemented by the following function, `searcher--form-fuzzy-regex`.

https://github.com/jcs-elpa/searcher/blob/e4e6666dcf812ed3c21c96b8c1ae83c48cad4a11/searcher.el#L132

The issue is that if the user was trying to search over `space`, `tab`, `newline (\n)`, `\r`, `\f`; the search cannot be processed due to the current fuzzy regular expression.

**Comment by EmberCS15** [comment]
Hey @jcs090218 , is it because of the regex specified  here in line [134](https://github.com/jcs-elpa/searcher/blob/master/searcher.el#L134)  ?

Is the requirement to allow matching to succeed even if any of these (space, \n, \t etc) occur after the regex? If you it would mean just removing `[^ \t\n\r\f]*` from the regex.

**Comment by jcs090218** [comment]
> Hey @jcs090218 , is it because of the regex specified here in line 134 ?

Hi! Indeed the line on 134.

> Is the requirement to allow matching to succeed even if any of these (space, \n, \t etc) occur after the regex? If you it would mean just removing [^ \t\n\r\f]* from the regex.

It's quite hard to explain, but I will try my best! :) 

The current implementation requires me to somehow take a string from buffer and then do the `flx-score` scoring algorithm. The line on 134 is indeed the regular expression I use to get the possible matching string. If I have removed `[^ \t\n\r\f]*` then the scoring part would not work well. For instance, if I have a string `buffer-file-name` and I am searching the string with input `bfn`. The score from `flx-score` should be high enough to get it but the string I am getting would be empty, which mean I not able to do the scoring base on this condition. Perhaps the implementation should mainly be these two tasks.

1) Use RegEx to get the possible fuzzy string
2) Score between the string and the input

But, I am also preventing it to get string too wide, like the following regexp `\\_<[bfn].*\\_>` will be very wide to the newline.

My first thought is to have a regular expression that holds the same character corresponds to the input. For example, if I have input `bfr i`. There is a space between `r` and `i`, then it should produce a regex that able to grab the context `buffer is` due to how many spaces are inside the input!

| Input | Match | Possible Regex |
|:---|:---|:---|
| `bfr i` | `buffer is` | Regex with limit of 1 spaces |
| `bfr i f` | `buffer is for` | Regex limit to 2 spaces |

But I am not very good at Regex so this feature is stalled for now. Mainly looking for help! 😕

**Comment by jcs090218** [comment]
I have replace my custom regex pattern to `ivy--regex-fuzzy`. I think this can be closed! Thanks!
